#include "lazurite.h"
#include "ml7404.h"

const RADIO_PHY_SET_T init_920MHz_DSSS_200kcps[] = {
    {RADIO_BANK_SEL_ADR              ,0x11},   /*!< [|BANK切り替え:BANK0]  */
    {RADIO_CLK_SET2_ADR              ,0xC3},   /*!< [|クロック制御2:クロックソースの選択 (TCXO使用時)]  */
    {RADIO_CH_SET_ADR                ,0x03},   /*!< [|RFチャネル設定:]  */
    {RADIO_ED_CTRL_ADR               ,0x83},   /*!< [|ED値平均回数設定数:]  */
    {RADIO_SYNC_CONDITION1_ADR       ,0x02},   /*!< [|受信プリアンブル設定:]  */
    {RADIO_SYNC_CONDITION3_ADR       ,0x01},   /*!< [|誤り許容設定:]  */
    {RADIO_MON_CTRL_ADR              ,0x00},   /*!< [|モニタ出力信号選択設定:]  */
    {RADIO_GPIO1_CTRL_ADR            ,0x00},   /*!< [|GPIO1端子(ピン#17)制御設定:]  */
    {RADIO_SPI_EXT_PA_CTRL_ADR       ,0x00},   /*!< [|SPIインタフェースIO /外部PA制御設定:SDO出力OpenDrain設定]  */
    {RADIO_DC_FIL_ADJ_ADR            ,0x15},   /*!< [|DCオフセット調整フィルタ設定:]  */
    {RADIO_PA_REG_ADJ_H_ADR          ,0x00},   /*!< [|PAレギュレータの出力電圧調整(上位ビット):]  */
    {RADIO_PA_REG_ADJ_L_ADR          ,0x89},   /*!< [|PAレギュレータの出力電圧調整(上位バイト):10dBm]  */
    {RADIO_CHFIL_BW_CCA_ADR          ,0x81},   /*!< [|CCA時チャネルフィルタ帯域幅設定:]  */
    {RADIO_BANK_SEL_ADR              ,0x22},   /*!< [|BANK切り替え:BANK1]  */
    {RADIO_RX_RATE1_L_ADR            ,0x04},   /*!< [|受信データレート変換設定1(下位バイト):]  */
    {RADIO_RSSI_MAG_ADJ_ADR          ,0x19},   /*!< [|ED変換用RSSI補正設定:]  */
    {RADIO_AFC_GC_CTRL_ADR           ,0x01},   /*!< [|AFC/ゲイン制御設定:]  */
    {RADIO_CRC_POLY1_ADR             ,0x08},   /*!< [|CRC生成多項式1:]  */
    {RADIO_CRC_POLY0_ADR             ,0x10},   /*!< [|CRC生成多項式0:]  */
    {RADIO_CH_SPACE_H_ADR            ,0x0B},   /*!< [|チャネル間隔設定(上位バイト):100kHz]  */
    {RADIO_CH_SPACE_L_ADR            ,0x61},   /*!< [|チャネル間隔設定(下位バイト):100kHz]  */
    {RADIO_VCO_CAL_MAX_N_ADR         ,0x04},   /*!< [|VCO_CAL_Max周波数設定:]  */
    {RADIO_BANK_SEL_ADR              ,0x44},   /*!< [|BANK切り替え:BANK2]  */
    {RADIO_NONPUBLIC_B2_ADR0E        ,0x52},   /*!< [|予約:]  */
    {RADIO_NONPUBLIC_B2_ADR16        ,0x55},   /*!< [|予約:]  */
    {RADIO_NONPUBLIC_B2_ADR19        ,0x08},   /*!< [|予約:]  */
    {RADIO_NONPUBLIC_B2_ADR1A        ,0x6E},   /*!< [|予約:]  */
    {RADIO_NONPUBLIC_B2_ADR1C        ,0x55},   /*!< [|予約:]  */
    {RADIO_NONPUBLIC_B2_ADR29        ,0xC6},   /*!< [|予約:]  */
    {RADIO_NONPUBLIC_B2_ADR2A        ,0x1F},   /*!< [|予約:]  */
    {RADIO_NONPUBLIC_B2_ADR2F        ,0xE7},   /*!< [|予約:]  */
    {RADIO_NONPUBLIC_B2_ADR32        ,0x4C},   /*!< [|予約:]  */
    {RADIO_GAIN_HHTH_ADR             ,0x8B},   /*!< [|高高ゲインから高ゲインへの切り替え閾値設定:]  */
    {RADIO_GAIN_HTOHH_ADR            ,0x3C},   /*!< [|高ゲインから高高ゲインへの切り替え閾値設定:]  */
    {RADIO_GAIN_HTOM_ADR             ,0x8B},   /*!< [|高ゲインから中間ゲインへの切り替え閾値設定:]  */
    {RADIO_GAIN_MTOH_ADR             ,0x3C},   /*!< [|中間ゲインから高ゲインへの切り替え閾値設定:]  */
    {RADIO_GAIN_MTOL_ADR             ,0x8B},   /*!< [|高ゲインから低ゲインへの切り替え閾値設定:]  */
    {RADIO_GAIN_LTOM_ADR             ,0x3C},   /*!< [|低ゲインから中間ゲインへの切り替え閾値設定:]  */
    {RADIO_RSSI_ADJ_H_ADR            ,0x2B},   /*!< [|高ゲイン動作時のRSSIオフセット値設定:]  */
    {RADIO_RSSI_ADJ_M_ADR            ,0x4D},   /*!< [|中間ゲイン動作時のRSSIオフセット値設定:]  */
    {RADIO_RSSI_ADJ_L_B2_ADR         ,0x7D},   /*!< [|低ゲイン動作時のRSSIオフセット値設定:]  */
    {RADIO_BANK_SEL_ADR              ,0x88},   /*!< [|BANK切り替え:BANK3]  */
    {RADIO_BANK_SEL_ADR              ,0x33},   /*!< [|BANK切り替え:BANK6]  */
    {RADIO_BANK_SEL_ADR              ,0x55},   /*!< [|BANK切り替え:BANK7]  */
    {RADIO_DSSS_CTRL_ADR             ,0x05},   /*!< [|DSSS制御設定:]  */
    {RADIO_DSSS_MODE_ADR             ,0x45},   /*!< [|DSSSモード設定:]  */
    {RADIO_FEC_ENC_CTRL_ADR          ,0x00},   /*!< [|FECエンコーダ設定:]  */
    {RADIO_FEC_DEC_CTRL_ADR          ,0x00},   /*!< [|FECデコーダ設定:]  */
    {RADIO_SS_AFC_RANGE_SYNC_ADR     ,0x04},   /*!< [|DSSS AFCレンジ設定(同期時):]  */
    {RADIO_SS_AFC_RANGE_ADR          ,0x04},   /*!< [|DSSS AFCレンジ設定(データ受信時):]  */
    {RADIO_SS_SYNC_BIT8_GATE_L_ADR   ,0x0C},   /*!< [|DSSS同期確立時相関閾値設定(下位バイト):]  */
    {RADIO_SS_SYNC_BIT8_GATE2_L_ADR  ,0x1C},   /*!< [|DSSS同期確立時相関閾値設定2(下位バイト):]  */
    {RADIO_SS_SYNC_BIT_GATE_H_ADR    ,0x00},   /*!< [|DSSS同期確立後相関閾値設定(上位3ビット:]  */
    {RADIO_SS_SYNC_BIT_GATE_L_ADR    ,0xD2},   /*!< [|DSSS同期確立後相関閾値設定(下位バイト):]  */
    {RADIO_SS_SYNC_BIT4_GATE_L_ADR   ,0x2C},   /*!< [|予約:]  */
    {RADIO_SS_SYNC_LOST_GATE_ADR     ,0x14},   /*!< [|予約:]  */
    {RADIO_AGC_AVE_OFST_SYNC_ADR     ,0x1A},   /*!< [|予約:]  */
    {RADIO_AGC_IIR_SET0_ADR          ,0x53},   /*!< [|予約:]  */
    {RADIO_AGC_IIR_SET1_ADR          ,0x25},   /*!< [|予約:]  */
    {RADIO_BIT8_SPDET_TH_L_ADR       ,0xF4},   /*!< [|予約:]  */
    {RADIO_DSSS_SET6_ADR             ,0x34},   /*!< [|予約:]  */
    {RADIO_DSSS_SET7_ADR             ,0x14},   /*!< [|予約:]  */
    {RADIO_DSSS_SET8_ADR             ,0x32},   /*!< [|予約:]  */
    {RADIO_DSSS_SET9_ADR             ,0x25},   /*!< [|予約:]  */
    {RADIO_BANK_SEL_ADR              ,0x99},   /*!< [|BANK切り替え:BANK10]  */
    {RADIO_BPSK_STEP_CTRL_ADR        ,0x10},   /*!< [|BPSKステップ制御設定:]  */
    {RADIO_BPSK_STEP_CLK_SET_ADR     ,0x01},   /*!< [|BPSKステップ制御クロック設定:]  */
    {RADIO_BPSK_STEP_SET0_ADR        ,0x20},   /*!< [|BPSKステップ制御設定0:]  */
    {RADIO_BPSK_STEP_SET1_ADR        ,0x11},   /*!< [|BPSKステップ制御設定1:]  */
    {RADIO_BPSK_STEP_SET2_ADR        ,0x21},   /*!< [|BPSKステップ制御設定2:]  */
    {RADIO_BPSK_STEP_SET3_ADR        ,0x21},   /*!< [|BPSKステップ制御設定3:]  */
    {RADIO_BPSK_STEP_SET4_ADR        ,0x21},   /*!< [|BPSKステップ制御設定4:]  */
    {RADIO_BPSK_STEP_SET5_ADR        ,0x51},   /*!< [|BPSKステップ制御設定5:]  */
    {RADIO_BPSK_STEP_SET6_ADR        ,0x43},   /*!< [|BPSKステップ制御設定6:]  */
    {RADIO_BPSK_STEP_SET7_ADR        ,0x34},   /*!< [|BPSKステップ制御設定7:]  */
    {RADIO_BPSK_STEP_SET8_ADR        ,0x44},   /*!< [|BPSKステップ制御設定8:]  */
    {RADIO_BPSK_STEP_SET9_ADR        ,0x54},   /*!< [|BPSKステップ制御設定9:]  */
    {RADIO_BPSK_STEP_SET10_ADR       ,0x65},   /*!< [|BPSKステップ制御設定10:]  */
    {RADIO_BPSK_STEP_SET11_ADR       ,0x66},   /*!< [|BPSKステップ制御設定11:]  */
    {RADIO_BPSK_STEP_SET12_ADR       ,0x66},   /*!< [|BPSKステップ制御設定12:]  */
    {RADIO_BPSK_STEP_SET13_ADR       ,0x34},   /*!< [|BPSKステップ制御設定13:]  */
    {RADIO_BPSK_STEP_SET14_ADR       ,0x36},   /*!< [|BPSKステップ制御設定14:]  */
    {RADIO_BPSK_STEP_SET15_ADR       ,0x55},   /*!< [|BPSKステップ制御設定15:]  */
    {RADIO_BPSK_STEP_SET16_ADR       ,0x35},   /*!< [|BPSKステップ制御設定16:]  */
    {RADIO_BPSK_STEP_SET17_ADR       ,0x36},   /*!< [|BPSKステップ制御設定17:]  */
    {RADIO_BPSK_STEP_SET18_ADR       ,0x23},   /*!< [|BPSKステップ制御設定18:]  */
    {RADIO_BPSK_STEP_SET19_ADR       ,0x21},   /*!< [|BPSKステップ制御設定19:]  */
    {RADIO_BPSK_STEP_SET20_ADR       ,0x01},   /*!< [|BPSKステップ制御設定20:]  */
    {RADIO_BPSK_STEP_SET21_ADR       ,0x00},   /*!< [|BPSKステップ制御設定21:]  */
    {RADIO_BPSK_STEP_SET22_ADR       ,0x00},   /*!< [|BPSKステップ制御設定22:]  */
    {RADIO_BPSK_STEP_SET23_ADR       ,0x00},   /*!< [|BPSKステップ制御設定23:]  */
    {RADIO_BPSK_STEP_SET24_ADR       ,0x00},   /*!< [|BPSKステップ制御設定24:]  */
    {RADIO_BPSK_STEP_SET25_ADR       ,0x00},   /*!< [|BPSKステップ制御設定25:]  */
    {RADIO_BPSK_STEP_SET26_ADR       ,0x00},   /*!< [|BPSKステップ制御設定26:]  */
    {RADIO_BPSK_STEP_SET27_ADR       ,0x00},   /*!< [|BPSKステップ制御設定27:]  */
    {RADIO_BPSK_STEP_SET28_ADR       ,0x00},   /*!< [|BPSKステップ制御設定28:]  */
    {RADIO_BPSK_STEP_SET29_ADR       ,0x00},   /*!< [|BPSKステップ制御設定29:]  */
    {RADIO_BPSK_STEP_SET30_ADR       ,0x00},   /*!< [|BPSKステップ制御設定30:]  */
    {RADIO_BPSK_STEP_SET31_ADR       ,0x20},   /*!< [|BPSKステップ制御設定31:]  */
    {RADIO_BPSK_STEP_SET32_ADR       ,0x22},   /*!< [|BPSKステップ制御設定32:]  */
    {RADIO_BPSK_STEP_SET33_ADR       ,0x21},   /*!< [|BPSKステップ制御設定33:]  */
    {RADIO_BPSK_STEP_SET34_ADR       ,0x22},   /*!< [|BPSKステップ制御設定34:]  */
    {RADIO_BPSK_STEP_SET35_ADR       ,0x32},   /*!< [|BPSKステップ制御設定35:]  */
    {RADIO_BPSK_STEP_SET36_ADR       ,0x53},   /*!< [|BPSKステップ制御設定36:]  */
    {RADIO_BPSK_STEP_SET37_ADR       ,0x55},   /*!< [|BPSKステップ制御設定37:]  */
    {RADIO_BPSK_STEP_SET38_ADR       ,0x63},   /*!< [|BPSKステップ制御設定38:]  */
    {RADIO_BPSK_STEP_SET39_ADR       ,0x43},   /*!< [|BPSKステップ制御設定39:]  */
    {RADIO_BPSK_STEP_SET40_ADR       ,0x66},   /*!< [|BPSKステップ制御設定40:]  */
    {RADIO_BPSK_STEP_SET41_ADR       ,0x66},   /*!< [|BPSKステップ制御設定41:]  */
    {RADIO_BPSK_STEP_SET42_ADR       ,0x56},   /*!< [|BPSKステップ制御設定42:]  */
    {RADIO_BPSK_STEP_SET43_ADR       ,0x45},   /*!< [|BPSKステップ制御設定43:]  */
    {RADIO_BPSK_STEP_SET44_ADR       ,0x44},   /*!< [|BPSKステップ制御設定44:]  */
    {RADIO_BPSK_STEP_SET45_ADR       ,0x43},   /*!< [|BPSKステップ制御設定45:]  */
    {RADIO_BPSK_STEP_SET46_ADR       ,0x34},   /*!< [|BPSKステップ制御設定46:]  */
    {RADIO_BPSK_STEP_SET47_ADR       ,0x15},   /*!< [|BPSKステップ制御設定47:]  */
    {RADIO_BPSK_STEP_SET48_ADR       ,0x12},   /*!< [|BPSKステップ制御設定48:]  */
    {RADIO_BPSK_STEP_SET49_ADR       ,0x12},   /*!< [|BPSKステップ制御設定49:]  */
    {RADIO_BPSK_STEP_SET50_ADR       ,0x12},   /*!< [|BPSKステップ制御設定50:]  */
    {RADIO_BPSK_STEP_SET51_ADR       ,0x11},   /*!< [|BPSKステップ制御設定51:]  */
    {RADIO_BPSK_STEP_SET52_ADR       ,0x02},   /*!< [|BPSKステップ制御設定52:]  */
    {RADIO_BPSK_STEP_SET53_ADR       ,0x00},   /*!< [|BPSKステップ制御設定53:]  */
    {RADIO_BPSK_STEP_SET54_ADR       ,0x00},   /*!< [|BPSKステップ制御設定54:]  */
    {RADIO_BPSK_STEP_SET55_ADR       ,0x00},   /*!< [|BPSKステップ制御設定55:]  */
    {RADIO_BPSK_STEP_SET56_ADR       ,0x00},   /*!< [|BPSKステップ制御設定56:]  */
    {RADIO_BPSK_STEP_SET57_ADR       ,0x00},   /*!< [|BPSKステップ制御設定57:]  */
    {RADIO_BPSK_STEP_SET58_ADR       ,0x00},   /*!< [|BPSKステップ制御設定58:]  */
    {RADIO_BPSK_STEP_SET59_ADR       ,0x00},   /*!< [|BPSKステップ制御設定59:]  */
    {RADIO_PADRV_CTRL_ADR            ,0x63},   /*!< [|PAドライバ制御設定:]  */
    {RADIO_PADRV_ADJ1_ADR            ,0x03},   /*!< [|PAドライバ調整1:]  */
    {RADIO_PADRV_ADJ2_H_ADR          ,0x02},   /*!< [|PAドライバ調整1(上位バイト):]  */
    {RADIO_PADRV_ADJ2_L_ADR          ,0x00},   /*!< [|PAドライバ調整1(下位バイト):]  */
    {RADIO_PADRV_CLK_SET_L_ADR       ,0x01},   /*!< [|PAドライバ制御用クロック設定(下位バイト):]  */
    {RADIO_BANK_SEL_ADR              ,0x11},   /*!< [|BANK切り替え:BANK0]  */
};
